### ISSUE TITLE
Change terminology from figure 'caption' to 'legend'

### ISSUE THREAD

**Issue by oliver----** [substance/texture#1085]
I have noticed that we are using the term figure 'caption' probably not correctly. It would be more common to name the fields in a Figure 'label', 'title', and 'legend'.

**Comment by JGilbert-eLife** [comment]
The `<caption>` element in JATS captures the combined title (`<title>`) and legend (One or more `<p>` following `<title>`). It does not contain `<label>` which is applied outside `<caption>` as a direct child of the object being labelled e.g. `<fig>`.

Therefore it's more accurate to say that a figure would have a label and a caption, with the caption being the composite of the title and legend.

I think that probably holds true for most colloquial uses of 'caption' since it's the structure reflected in JATS. It refers specifically to the descriptive text accompany an object whereas 'label' is the human-readable identifier for the item. 

Not sure how much that really matters for the Texture display though!

**Comment by oliver----** [comment]
Just don't want to use confuse with using terms incorrectly.
After what you said, it would still be better to name fields 'label', 'title', and 'legend'.
Correct?

**Comment by JGilbert-eLife** [comment]
Absolutely, and apologies for not being so succinct!

**Comment by oliver----** [comment]
Thanks! 😄

**Comment by oliver----** [comment]
Done.
