### ISSUE TITLE
Improve 'Download File' in desktop app.

### ISSUE THREAD

**Issue by oliver----** [substance/texture#1132]
ATM this opens a link in the same window. This makes the app unusable afterwards.
We should discuss if we need this feature for the desktop app at all, and if so, then we need an explicit mechanism opening a file dialog similar to 'Save as'.

**Comment by oliver----** [comment]
IMO, we should implement the file-dialog mechanism. Even if we decided to disable the save file command in electron, we would probably want something for a future DAR browser.

**Comment by oliver----** [comment]
@Integral what was the reason why you disabled this for electron in first place? https://github.com/substance/texture/blob/master/src/article/editor/DownloadSupplementaryFileTool.js#L12

**Comment by Integral** [comment]
@oliver---- Can I ask you to provide more details regarding application unusability after downloading supplementary file? Is there any error, if so what build did you used, in what OS?
I see that file got downloaded in macOS High Sierra and the app is working afterwards. Still there is a big problem that you have no chance to understand that file got downloaded. True, I introduced this exception for electron since with new window after downloading you'll see a blank window:
<img width="1030" alt="screen shot 2019-02-03 at 14 52 44" src="https://user-images.githubusercontent.com/182010/52176465-2b988580-27c4-11e9-9278-101ac1ab11d4.png">
I think it is rather annoying and confusing. I believe we should try to find some general approach for downloads in desktop app, let's discuss it.

**Comment by Integral** [comment]
@oliver---- thanks for gif!
Can I ask you what branch did you use? Perhaps you can attach a dar file?
Because I don't have this problem with mac os:
![](http://g.recordit.co/GFdHa68wKH.gif)
I not even sure that new window will solve the problem for you. So as a first step I think we should try to understand what's going on.
I also found a problem with attached image as supplementary file. It's not downloading, but opening:
![screen shot 2019-02-03 at 20 11 42](https://user-images.githubusercontent.com/182010/52179824-f4d86480-27ef-11e9-80fa-8a59329a182c.png)

**Comment by oliver----** [comment]
Yes, opening tab is not a solution, but doing in the same tab is worse.

I am on master. Also for me it's opening the file. The one from the capture was very large and it finished after gif ended.

As I have described in the issue description, we need something different: a file save dialog. Similar as our 'Save as'. And instead of opening the tab we need to 'read' data from that url and pass it through to file write.

**Comment by Integral** [comment]
@oliver---- I think we can force saving the image via `download` attribute of <a> tag. I think that would be better rather than showing it... What do you think?
I will try to implement save as in separate PR.

**Comment by oliver----** [comment]
If that is possible, it's better. Would that work for electron, too?

**Comment by Integral** [comment]
I will investigate ;)

**Comment by Integral** [comment]
Re: download attribute. It will instructs browser and electron to download a URL instead of navigating to it, so the user will be prompted to save it as a local file, but only for same-origin URLs. In other words: it will not work for remote images.

**Comment by oliver----** [comment]
In the browser it did download remote files with the target=_blank, though

**Comment by Integral** [comment]
yes, but not images

**Comment by oliver----** [comment]
Ok, then let's collect a list of cases and options to summarise what we can do in which situation.

**Comment by Integral** [comment]
To my surprise I don't see a lot of options for image downloading in client, I only found [this](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image) technique. Which is a bit too much in my taste and a bad sign for solving this problem. I mean if there is a move towards image download restriction maybe we should consider that and rather show image with some additional warning.
So a list of cases is following:
1. Browser version
  1.1. Local image (working fine with new page and download attribute)
  1.2. Remote image (going wild with canvas or show image or show image with warning [a div with 100% max-height and max-width and warning on top of it])
  1.3. Anything else (working fine with new page)
2. App version
 I believe we can do anything through file dialog an piping GET result to a file.

**Comment by oliver----** [comment]
Maybe there we will extend the dar-server protocol to retrieve a download url from the server, then this can be proxied if needed.

**Comment by Integral** [comment]
@oliver---- Is it correct for Browser use case: we are opening any file in new tab with @download (we just know that it will not work only for remote images and for now don't want to display warnings)?

**Comment by oliver----** [comment]
I suggested to do `target=_blank` for remote. Because there is no better way.

**Comment by Integral** [comment]
Ok. Got it. Priority?

**Comment by oliver----** [comment]
Rather sooner, than later, because currently it is kind of broken.

**Comment by Integral** [comment]
Ok, I will try. Unfortunately it's not super trivial for app.

**Comment by Integral** [comment]
@oliver---- may I ask you to try #1134 in app?
looks like electron have a [special api](https://electronjs.org/docs/api/download-item) for our case

**Comment by Integral** [comment]
For me it works exactly as we discussed, but curious about original case of yours. How it will look like?

**Comment by oliver----** [comment]
It is working - almost :)
It crashes on 'Cancel'.

**Comment by oliver----** [comment]
Done via #1134
