### ISSUE TITLE
Desktop App should show 'Texture' as application name

### ISSUE THREAD

**Issue by oliver----** [substance/texture#1133]
![image](https://user-images.githubusercontent.com/284099/52173748-7bf2f180-278a-11e9-9cf5-dee7d2d9b039.png)

**Comment by Integral** [comment]
@oliver---- are you running desktop app through electron cli? Do we want to cover this case? Because I believe that if you install it you'll see this picture:
<img width="445" alt="screen shot 2019-02-03 at 14 35 19" src="https://user-images.githubusercontent.com/182010/52176237-f5a5d200-27c0-11e9-9459-9a996350089a.png">

**Comment by oliver----** [comment]
Of course! Sorry, me stupid.
