### ISSUE TITLE
substitute ‘sub-figure’ with ‘panel’

### ISSUE THREAD

**Issue by evabenitoembo** [substance/texture#1156]
![image](https://user-images.githubusercontent.com/31538460/52275859-038a5d00-2951-11e9-97cb-94e25935a3e7.png)

**Comment by michael** [comment]
What if we just call it "Figure"? To avoid the technical term, and I think it's clear based on the context when you are dealing with a group of figures (aka sub-figures).

**Comment by oliver----** [comment]
I'd suggest the following re-wording:
- Add Figure
- Remove Figure
- Move Figure Down
- Move Figure Up
- Open Image
- Replace Image

**Comment by source-data** [comment]
Well, it is an important point and I think it is difficult to re-define the terminology for users. I dont' think it would be clear to most users that we mean "_Panel_" when we write "_Figure_". Users will have very different expectations for "_add a figure_" from "_add a figure panel_" or "_add a sub-panel_".

Figures are a bit special. They are really very very well established elements and many many authors start 'writing' their papers by actually assembling multi-panel figures. Since 90% of figures in the life sciences have panels, there is a rather strong practical justification for being clear and following this de facto standard. 

I know that it is a bit of a pain because for some reason this pervasive structure might not be capture explicitly in JATS under these terms and we have to use "figure groups" as a workaround but this should stay under the hood. For users, I think we should be straighforward and follow the dominant 'behavior'.

**Comment by oliver----** [comment]
I guess we were thinking that 'Panel' is a too technical term. But I am fine with that, too.

**Comment by source-data** [comment]
yes, well, I am open really between Panel and Sub-figure. We can ask users what the prefer. It is just the concept of "figure" that should be clear. We all agree :-)

**Comment by oliver----** [comment]
Done via #1169
