### ISSUE TITLE
ReproducibleJATS: <fig>

### ISSUE THREAD

**Issue by michael** [substance/texture#253]
We are adding support for reproducible elements to JATS and Texture. Here's a first proposal on how we could model and display reproducible figures. The tagging guideline below was developed in June during a workshop at eLife.

```xml
<fig id="f1" fig-type="reproducible-chart">
  <label>Figure 1</label> <!-- label is auto-generated -->
  <caption>
    <title>Biodiversity on Mars</title>
    <p>Lorem ipsum</p>
  </caption>
  <alternatives>
    <code specific-use="source" language="mini">
      scatter3d(co_occurence_matrix)
    </code>
    <!-- static version for existing JATS toolchains -->
    <graphic specific-use="output" xlink:href="89f8b53e361f.png"/>
  </alternatives>
</fig>
```

In the user interface (if reproducible content is enabled) a new reproducible figure can be created via `Insert -> Reproducible Figure`. Next, the user can enter an expression that produces an output (e.g. an interactive graphic). It is important that a static image is created as well, this we can then encode as a graphic and use in static versions (e.g. HTML or PDF) of the manuscript.

![image](https://user-images.githubusercontent.com/2931/30059271-b0683746-923e-11e7-815d-7dbae67f6e98.png)

**Comment by axfelix** [comment]
I don't think we have any requirement for Figures to support more than caption + static graphic, so this *should* be a superset of our needs. @jalperin ?

**Comment by michael** [comment]
This a spec for reproducible figures, they will be handled in a separate/independent implementation. I'll open a new issue for regular (static) fig elements soon. Please start off with checking the following issues meanwhile:

https://github.com/substance/texture/issues/238 element-citation - we need a full spec for all pub types that should be supported, currently we only covered book and journal and those are also not final

https://github.com/substance/texture/issues/240 aff - please verify the latest proposal if good enough for you needs

https://github.com/substance/texture/issues/239 contrib and name - please check and add comments

**Comment by axfelix** [comment]
Sorry for hijacking this issue, but I notice the last issue I reported Texture `<fig>` validation problems in has been closed. I finally made some changes to our output so that label, caption, etc., are not children of `<graphic>` anymore but rather siblings in anticipation of Alpha 4, but it seems like Alpha 3 still doesn't like them:

<label> is not allowed at the current position in <fig>. (object-id*,label?,caption*,abstract*,kwd-group*,(alt-text|long-desc|email|ext-link|uri)*,(disp-formula|disp-formula-group|chem-struct-wrap|disp-quote|speech|statement|verse-group|table-wrap|p|def-list|list|alternatives|array|code|graphic|media|preformat)*,(attrib|permissions)*)
<fig position="float" orientation="portrait">
  <graphic xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/manager/xml/id/1971/media/image1.png" id="IDfa71a724-bc0b-40f6-ac3b-b8af5ef40cf6" position="float" orientation="portrait" xlink:type="simple">...</graphic>
  <label>...</label>
  <caption>...</caption>
</fig>

Is this behaviour expected to be different in Alpha 4?

**Comment by michael** [comment]
Hey! Cool you adjusted the converter! 👍 

In Alpha 4 we'll support the following spec: 

https://github.com/substance/dar/blob/master/specs/JATS4M.md#figures

`label` and `caption` must go before `graphic`. Could that also be changed in the converter?

Also note, that labels will be overridden by Texture (we'll make that label generator configurable).

**Comment by axfelix** [comment]
Think I just fixed that, but I'm hitting whitescreens on fig elements now...
[document.xml.txt](https://github.com/substance/texture/files/1640945/document.xml.txt)

(It's possible we've already been over this and I'm back to producing a result that will be good in Alpha 4, just confirming).

**Comment by michael** [comment]
Repro-figs are spec'ed and implemented. Closing.

@axfelix will check your posted example but respond separately.
