### ISSUE TITLE
JATS4M: spec for <fig>

### ISSUE THREAD

**Issue by michael** [substance/texture#265]
## `<fig>`

```
object-id[pub-id-type=doi]?, label?, caption?, graphic
```

Example: 

```xml
<fig id="f3" position="float">
<!-- Note, label is auto-generated by Texture, not entered by the user -->
<label>Figure 3.</label>
<caption>
<title>This is the figure that shows everything</title>
<p>Lorem ipsum</p>
</caption>
<graphic xlink:href="1.4821168.figures.highres.f3.zip"></graphic>
</fig>
```

Questions:

- should we include label? label is weak display information, which could be generated (texture does that)
- ok to not include media, as it can be represented standalone? (e.g. see eLife tagging for media)
- do we need alternatives? If yes what are the use-cases?

*Please help improve and finanlize this spec. It will be used for realizing the Texture user interface.*

**Comment by oliver----** [comment]
I think that `object-id[pub-id-type=doi]` should not be mandatory.

**Comment by cinthia-vieira** [comment]
Michael, I have a question about the figure label auto-generating:

In which languages the generating will be supported? Since in SciELO we work with a mininum of 3 languages (Portuguese, Spanish and English), an auto-generating tool that does not have other options besides English does not contemplate our publishing context.

Also, we have to consider that there are cases when the images are not labeled as "figures", as it can be a graphic chart, a schema or other kind of graphic representation of data. I think it'd be intersting to let this open to the user filling it, as an image can be used in different ways in an article.

**Comment by michael** [comment]
Hi @cinthia-vieira! So my preferred approach would be to not store the labels in the JATS at all. While editing in Texture we generate those english labels, and later when you publish the article you could use your own tools to generate labels in your preferred style.

- if it is important that things in Texture look closer to the published result, we'd need to add configuration to texture so a custom label generator can be provided, it's possible to do that but i think there's more important things to do first. Let me know what you think.

**Comment by michael** [comment]
@Melissa37 how would you feel about dropping the label from fig elements in the source XML? I'm asking because if I think in it's purest form, the source format would not determine labels at all, instead they could be computed by the toolchains that generate the HTML page or PDF. The same would go for xrefs, where we could remove the label text and let the production tools compute the citation style. There would be some elegance in not solving label generation in Texture, and leaving this to the presentation layer. There tools like Citeproc could be easier integrated, than in the editor directly (technical reasons). Also multi-lang is an issue as mentioned by @cinthia-vieira, which could be solved outside of the source editing.

I'm aware this is more of a radical change but wanted to hear your thoughts on it generally.

**Comment by Melissa37** [comment]
Hi @michael thanks for asking.

Here are my thoughts on it! Not blockers, but for consideration I think!

The JATS4R recommendation: http://jats4r.org/display-objects
Labels: <label>. If the object has a label (e.g., “Fig. 1”, “Table 2”, “Box 1.1”) and this information is to be captured in the XML (rather than generated by a style sheet), then contain this information within <label>, and not within <caption> [[Validator result: Warning if label-like thing is found in caption text rather than in <label> ]]
Titles: <caption>, <p>, <title>. If the object has a title that is obviously separate from the main caption text (for example, if the first sentence is the title), then contain this information within the <title> element inside <caption>. Put the remainder of the caption within <p>, after <title>.
Do not use labels (such as “Fig. 1”) within <title> or <caption><p>; use <label> instead (see Recommendation 9, above). [[Validator result: warning if sentence starts as “Fig”/”Table”/”Box” ]]

I understand your idea that "source format would not determine labels at all, instead they could be computed by the toolchains that generate the HTML page or PDF".
However, 2 issues:
I think PMC requires labels for deposition to them and for the reusability of content it is useful to have labels as not all style sheets or systems will account for this?
In our systems they are editable so we can make tweaks to the "editorial" style of titles - for instance very occasionally we've changed "figure 1" to "scheme 1" as this is what it should be for display from the author/reader point of view. However, the item is a figure and is displayed like a figure everywhere so would not be called something else. So, we would not add the label via a style sheet.

I hope that is helpful? Can you provide a screenshot of the system as it looks now?

**Comment by michael** [comment]
Thank you @Melissa37! I'm getting a better sense of the use-cases. Tried to come up with a proposal how this could be solved using a post-processor that ships with Texture and can be configured and integrated by publishers into a journal management system.

Read the proposal here: #273  (would that be a valid approach?)

> Also, as we're working on an author writing tool - how would the author reference the figure without using the label? Maybe I need to have a live demo of what you have so far if I am missing the point :-)

There's id's for everything that can be referenced. The user does not need to express a reference by convention like.. putting "Figure 1" into the text. Instead they just choose from all existing figures in a dropdown (listed in the order of their occurence in the document, which could change at any time).

![image](https://user-images.githubusercontent.com/2931/30671318-9700a926-9e66-11e7-91b2-855801b2072c.png)

**Comment by Melissa37** [comment]
Thanks @michael for the explanation!
So, the idea is that the author bungs in figures and references them whenever s/he wants and then as they go along they get ordered?

One user testing issue to consider - what if the author has 20 figures - is that going to become an unwieldy situation?

**Comment by JGilbert-eLife** [comment]
The one important use-case I can see that probably ought to be accounted for is that an author may wish to reference a figure before they introduce it. So, for example, between what they think of as 'Figure 1' and 'Figure 2', they may wish to mention 'Figure 6' without actually reordering the figures - e.g. they still want Figure 6 to be primarily associated with a later point in the text, but want to mention it before that.

Obviously with the lens style viewer, this doesn't work the same way that it would in a linear presentation but I still think this is something authors might want - I get the impression the order of figures is usually quite important for authors, over and above the order in which they are cited.

**Comment by michael** [comment]
You can try this out here: http://cdn.substance.io/texture-alpha-3/

E.g. cut and paste a figure into a new location. 

I think 20 and more figures should be managable in a dropdown with a vertical scrollbar, but I think we should generally add filtering capabilities to this dialog.

**Comment by axfelix** [comment]
We'd like to accommodate `label` and `caption` being children of `graphic` at least as input, as this convention seems to be used by more than one of our parsing libraries, but I'm OK with it being coerced into the proposed structure on import.

**Comment by pigeonm** [comment]
Hi, 

About the label of a figure : 

For Erudit it is important to be able to override the default label name. Firstly because we publish journals in several languages (french, english and spanish), but also because the authors sometimes customize the label of their figures.

**Comment by pigeonm** [comment]
About the source of a figure : 

Also, you are not talking about the source of a figure in this discussion, but we guess that, since it is a JATS4R recommendation, the source will be tag in "permission" ? According to the use cases we have on Erudit, we find that the “permission” tag is too restrictive. For example, if the source of a figure says "2017, Photo courtesy of Family Food Research Practices", I do not want to be forced to finely tag the copyright statement, the copyright holder and the copyright year. So, for us, the “attrib” tag (JATS 1.1 but not a JATS4R recommendation), which can contain text, would fit better our needs.

**Comment by Melissa37** [comment]
Hi there

I've done a quick cross check and what's missing from spec for JATS4R requirement:
@id on <fig> is mandatory
mime-type
permissions

@pigeonm re the permission recommendation, it's not intended to be so restrictive and this is good feedback, thank you.

The example you give above would fit into the JATS4R recommendation, see this example:

```xml
<fig id="fig1">
 <label>Fig. 1</label>
 <caption>...</caption>
 <!--Here, this particular image is published under a copyright that is different from the one that applies to the article a whole (and is, in fact, all rights reserved).-->
 <permissions>
 <copyright-statement>The National Portrait Gallery, London. All rights reserved</copyright-statement>
 <copyright-year>2013</copyright-year>
 <!-- Note: no license element here: all rights reserved. -->
 </permissions>
 <graphic xlink:href="images/fig1"/>
 </fig>
```

This was a founding recommendation of JATS4R and one of the reasons it was set up - so re-users of content would explicitly know what they can and cannot reuse. It would be a shame for this to not be supported. I feel strongly about this one. Could you provide other examples where it does not work for you?

Thanks!

**Comment by pigeonm** [comment]
@Melissa37, ok, thanks for the explanations!
@michael we are OK with what is proposed about the <fig>. The JATS4R recommandation exemple is very close to the way we tag figures.

**Comment by michael** [comment]
Thank you everyone for the fruitful discussions here. I've consolidated all the specification work into a single document: https://github.com/substance/texture/blob/master/docs/JATS4M.md

I will close this issue now, as I think we created a good base. Please open new issues anytime if you have questions, suggestions how to improve the current spec.
