### ISSUE TITLE
Document save button vs. autosave behaviour

### ISSUE THREAD

**Issue by axfelix** [substance/texture#330]
Hi,

We'd like to finalize our behaviour for incrementing drafts when using Texture -- is there documentation of how the final autosave vs. save-button behaviour is intended to work, and are the hooks stable?

**Comment by axfelix** [comment]
Bump :)

**Comment by michael** [comment]
Hey! Sorry I missed that issue. The save functionality will change with the new release. Instead of the readXML writeXML hooks, Texture will take a so called DocumentArchive instance (see https://github.com/substance/dar) which is manipulated in memory, including assets etc. We also like to remove the save button from the Texture interface, as that is something the integrated app should take care of. There you can also decide wether to do auto save or explicit saving, or both.

New Texture usage will look like this:

```js
OJSDocumentArchive.load('doc-25234').then(documentArchive => {
  let texture = Texture.mount({ documentArchive }, document.body)
  
  texture.on('change', () => {
   documentArchive.save().then(() => {
     console.log('autosave complete...')
   ).catch(err => {
     console.error(err)
   })
  })
})
```

All you need to do is implement the DocumentArchive interface for OJS, we will provide an example, when ready.

**Comment by axfelix** [comment]
OK, great -- sounds good.

Would explicit saving just entail adding a button to call `documentArchive.save()` without wrapping it in a `texture.on('change')`? And is there good documentation for adding / removing buttons to the texture toolbar? I want to make sure we're able to implement this as quickly as possible because (other than the figure upload backend) it's the only major detail we still need for going to production.

**Comment by michael** [comment]
Exactly. With respect to the save button+behavior, we are pulling that out of the Texture editing interface, so your integration can decide what to do.

We are working on a reference implementation in node for the storage adapter (will share when ready). I assume you may want to implement that service in PHP, which will require some coordination / coding effort on your side. We should do some planning.

**Comment by michael** [comment]
Solved.
