### ISSUE TITLE
RFC: QC-optimised interface

### ISSUE THREAD

**Issue by michael** [substance/texture#338]
![image](https://user-images.githubusercontent.com/2931/34962933-374cfe1c-fa46-11e7-8d5f-45b1893c6f69.png)

Worked on sketching a more functional interface optimised for data quality checking at publishers.

Goals:
- show all info needed to perform quality checking task
- easily add/remove/edit authors/editors
- click on affiliation brings up an edit dialog directly
- attach article-specific information to an author (e.g. contribution, and competing interests)

Please add your comments!

**Comment by axfelix** [comment]
Just clarifying -- the scope here is for a QC interface for front matter only, right?

**Comment by michael** [comment]
There's more to be designed, just wanted to start with those front-matter items to find a good direction.

**Comment by michael** [comment]
Idea is to put everything into the main content section, to see everything at a glance. 

Here's more (not beautiful but easy to scan through vertically):

![image](https://user-images.githubusercontent.com/2931/34964108-39c62cd0-fa4c-11e7-84ac-35a3f109a29f.png)

Maybe worth considering to make certain sections collapsible/expandable.

**Comment by Melissa37** [comment]
Love the first screenshot, looks really good!
Re ORCID - they have rules about presentation, sorry! 
https://orcid.org/trademark-and-id-display-guidelines
![screen shot 2018-01-16 at 08 36 53](https://user-images.githubusercontent.com/6051876/34979125-5a7f74a8-fa98-11e7-8edb-86f09f3fecc4.png)

Re content section 
I am not sure what Content location means - if this will be displayed I think the term needs changing?
I don't think there is need for a page range and f and l pages - one should populate the other? Or they could be displayed, but one autofills the other, otherwise users will think they have to fill in both?
But presumably this would be configurable per publisher?

Thanks, looking good!
M

**Comment by gmaciocci** [comment]
I think the overall flow of the 1st screenshot is ok, but its over-reliance on lines, boxes and separators (instead of typography, font hierarchy and white space) makes it look a lot busier than it needs to be. I also can't tell whether you're showing those panels in their normal state or in their editable state (editable text fields seem active, but the button labels suggest you need to activate "edit" mode first).  

I assume this is just a special "all info at a glance" QC / submission metadata view and not the default view an author would see of their paper when tweaking it? I'm somewhat worried about how it would scale on papers with massive author lists, for instance. Perhaps a collapse/expand mechanic with an "expand all" button somewhere might provide the right compromise?

**Comment by michael** [comment]
@Melissa37 re ORCID, I guess these rules only apply for things that have been published and appear on the web? We could show the icon, but I'd try to rather use explicit labels instead of icons.

`page-range` would be more powerful, but needs to be parsed. If we showed only page range we'd need to enforce a strict format so we can parse it. E.g. `1-5;10-15` would translate to `fpage: 1, lpage:5`. Would that work?

@gmaciocci I tried it without boxes at first, but felt it's getting too hard to recognise individual authors. Also, we need some way to change the order of authors (small bar to the left is draggable). The reason why you see editable fields + an edit button is that some information is stored as an entity (reusable person record, with affiliations, e.g. the same person record could be used in a citation) while the other elements are article-related (e.g. contribution, equal contribution flag). There's a lot of info to capture, and it gets quite busy. Maybe we could make a custom, combined edit form that has the person info as well as the article-specific data, as the user does not care about the difference. I will work on another mock...

**Comment by Melissa37** [comment]
@michael thanks! But if eLife were using it, we'd need to follow their rules, it's for display anywhere.
I think f page/l page would be best to enter, then that geenrates the range (which would be harder to enforce strict criteria and it be followed in order to populate the other fields. However, that requires more entry effort?
If this is for the details of the actual article, it's a one-time effort so could be OK. It does not affect eLife though as we use elocation and have no pages, so I'll leave it to those it would affect to comment :-)

M

**Comment by michael** [comment]
Those ORCID folks are so strict 😄. 

Here's a new sketch. @gmaciocci that better? Would bring up a combined edit dialog, with all fields from the person record + article-specific bits.

![image](https://user-images.githubusercontent.com/2931/34987982-689a88aa-fabd-11e7-8c1d-963188804de5.png)

**Comment by gmaciocci** [comment]
@michael much cleaner!

**Comment by NickDuf** [comment]
@michael, a couple of observations. Feel free to take or leave this feedback as I am a little late

- Is the article title supposed to editable from this panel? If so why are some areas editable by clicking a link and others editable by default?
- The vertical space could be used better to organise the info - try using a baseline grid (see baseline grid comp) 
- In between each author I would suggest a light divider to help organise the information for scanning purposes. It would also help to anchor the edit and delete links
- A little more variation in typography might help. Section labels could be all caps or styled in a way that more clearly distinguishes them against the more important text
- I find the type input pattern to create new editors and authors unusual. A more typical flow is New item > the input appears and then you type into the input while it offers suggestions. The issue is that you are assuming the system has someone in the first instance otherwise you then offer the create new control. In my experience this is not always the case and obviously makes the pattern harder to reuse else where
- Some comps below

![detail qc vertical grid 2x](https://user-images.githubusercontent.com/12328191/35222568-0aaba520-ff87-11e7-8213-5d6baa9d962e.png)
![detail qc 2x](https://user-images.githubusercontent.com/12328191/35222569-0ac84054-ff87-11e7-9e2e-af7aa28154d8.png)

**Comment by michael** [comment]
Good points @NickDuf ! Also thanks a lot for that clean mockup! 

I'm aware that it causes confusion that some parts are editable directly while others need a dialog. But I don't have an idea yet how to avoid that, unless we use a separate panel for all metadata. 

For explanation: The rule is that article-specific content can be edited in place (any keystroke can be undone just like in MS Word), however if you are editing a person or organisation record, this will be changed in a form and confirmed with an explicit click on Save. Conceptually this kind of data isn't actually part of the article, it's stored globally and only referenced from the XML.

There's a similar thing you can observe in Google Docs. Comments are external, and not part of the undo history. They are also not saved on each keystroke but need an explicit confirm.

However, we should try our best to avoid that technical details are affecting the user interface. We'll discuss how your suggestions could be implemented and get back to you.

**Comment by NickDuf** [comment]
@michael no problem. I would be interested to know how the user gets to this panel? is it activated from clicking an author name on the manuscript, or triggered from another individual author edit panel? Just wondering if the article title input needs to be there if it is already adjustable using textures manuscript view.

**Comment by michael** [comment]
I would still show the full manuscript in the QC view and be able to edit it. So the QC view is just a more detailed authoring view.

Maybe there's a way to make a visual distinction between directly editable parts (title, abstract, manuscript body) and things that need an edit dialog.

**Comment by NickDuf** [comment]
@michael more than happy to look at this with you if you wish?

**Comment by michael** [comment]
Thank you @NickDuf, can I ping you some time next week?

**Comment by NickDuf** [comment]
@michael totally fine.

**Comment by michael** [comment]
We discussed an idea today, which would bring up task-related QC panes, which then are displayed as a modal. For instance, one could bring up the "Check Authors and Affiliations" pane, which will point out issues and let you fix them in a dedicated interface. Once you've made your changes you can hit save and you'll return to the manuscript view.

![image](https://user-images.githubusercontent.com/2931/35858051-5b43798a-0b3b-11e8-868d-2171855f579f.png)

Thoughts?

**Comment by fabiobatalha** [comment]
@michael 

It seems to be a good approach.

Is it time to define what information we want to edit with this feature or we will talk about it in a different ticket and moment?

**Comment by michael** [comment]
Definitely! Please list all the info you want to have exposed. Next we‘ll
update the JATS4M spec, and once everyone is happy we can start
implementing.

**Comment by fabiobatalha** [comment]
Journal

- journal publisher id
- journal aggregator id
- journal other id
- Title
- Abbreviated title
- other titles
- ISSN (electronic, print, other)
- publisher name

Issue

- volume
- number
- publication date
- received date
- reviewed date
- acceptance date
- Issue Title

Article

- Article ID (DOI, publisher ID, aggregator ID)
- pages (first, last)
- elocation
- translated titles
- abstract and translated abstracts
- keywords and translated keywords
- Document Type (Original Article, Review Article, etc)
- Author Notes
- Editorial Notes
- Bio Notes [example](https://www.erudit.org/fr/revues/mi/2011-v16-n1-mi1826189/1006917ar/#nb1)  look for "notes biographiques"
- acknowledgements [example](https://www.erudit.org/fr/revues/rse/2011-v37-n1-rse01/1007666ar/)
 look for "remerciements"

**Comment by michael** [comment]
We have taken a different path for the QC interface. Closing this, and opening a new issue regarding your requirements @fabiobatalha. See https://github.com/substance/texture/issues/618
