### ISSUE TITLE
New to Texture (How do you create/save/export)

### ISSUE THREAD

**Issue by fredhampton** [substance/texture#455]
I m new to Texture. I'am using the current browsers based versions.

How do you create new documents ?

How do you save documents ?

Is there a way to export documents ?

**Comment by michael** [comment]
You can download a Desktop version here: https://github.com/substance/texture/releases

Then you can create and save documents on your disk.

**Comment by fredhampton** [comment]
@michael Is there a way to have the same functionality in the browser version ?
I would like to have my entire work flow in the browser and have texture as an open tab.


All thanks to you 

Wiliam

**Comment by michael** [comment]
Yes you can have the same functionality in the browser. We have developed a storage backend in Node.js that can be used for storage, but you could also implement the same API in a different server-side language.

https://github.com/substance/dar-server

We don't provide a full-stack solution, because we want to focus on developing the text editor interface. So integration and publishing workflows are the integrator's responsibility.

**Comment by curseagain** [comment]
@michael this might be useful information to provide on the demo pages!
