### ISSUE TITLE
It should be possible to choose the file name while saving on the desktop app.

### ISSUE THREAD

**Issue by gustavofonseca** [substance/texture#466]
When saving the file it is possible to choose the target directory but it is not possible to choose the file name. The result of the save action is always the creation of the files manifest.xml and manuscript.xml.

I'm using the version 1.0.0-preview.1 (1.0.0-preview.1) on MacOS High Sierra.

**Comment by michael** [comment]
The current behaviour is intentional as we want to move away from single XML files which are separate from assets (e.g. images, videos) towards an archive format, which essentially is a folder. Having it as a folder has is the most open one (e.g. you can use version control like Git) but we could also support a compressed single file that's then easier to share (e.g. `mydoc.dar`).

Let's discuss this in Cambridge.

**Comment by michael** [comment]
We store .dar files now.
