### ISSUE TITLE
Including author footnotes

### ISSUE THREAD

**Issue by JGilbert-eLife** [substance/texture#538]
Support for contribution, conflict of interest and additional footnotes is required for authors.

```

<xref ref-type="fn" rid="conf1"/>

<xref ref-type="fn" rid="con1"/>

<xref ref-type="fn" rid="fn1">&#035;</xref>

.
.
.

<fn fn-type="COI-statement" id="conf1">
          <p>Chair of JATS4R</p>
</fn>

<fn fn-type="con" id="con1">
          <p>Completed the XML mapping exercise and wrote this XML example</p>
</fn>

<fn fn-type="fn" id="fn1">
          <label>&#035;</label>
          <p>This footnote text must work in isolation as nothing is processed on the html view to make it "work".</p>
</fn>

```

**Comment by Melissa37** [comment]
Note - there is a JATS4R recommendation for clinical trials now: https://jats4r.org/clinical-trials
eLife will be implementing that soon.

**Comment by michael** [comment]
I have a feeling this could be done more elegantly as attributes or elements of `contrib`. I know we are missing some elements in JATS but to me this should look something like this:

```xml
<contrib>
  <name>...</name>
  <texture:conflict-of-interest>Chair of JATS4R</texture:conflict-of-interest>
  <texture:contribution>Completed the XML mapping exercise and wrote this XML example </texture:contribution>
</contrib>
```

Is there really a need for arbitrary footnotes for authors? Or could such information go into the bio for instance? I think we would benefit a lot by structuring this information instead of assigning footnote references (which are pretty much print-style oriented). An advantage of a property/attribute is that it can only occur once and thus is very easy to process.

@Melissa37 I'm more and more thinking that even introducing custom elements/attributes (as extensions) could make sense. In the end we just need a simple way to capture structured information (think a database record). On save we can store an additional article.archive.xml version, that conforms to JATS4R and adds redundant information required by PubMedCentral (e.g. footnotes).

**Comment by michael** [comment]
This needs better specification. Don't want to realise this as abritrary footnotes in the editor. Better see this as number of fields to fill out per author.

@JGilbert-eLife when is something like this (with custom label) needed?

```xml
<fn fn-type="fn" id="fn1">
          <label>&#035;</label>
          <p>This footnote text must work in isolation as nothing is processed on the html view to make it "work".</p>
</fn>
```

Can we somehow avoid that?

**Comment by Melissa37** [comment]
Please see: https://jats4r.org/conflict-of-interest-statements for conflict of interest - eLife will update tagging to conform with the JATS4R recommendation

https://gitlab.com/JATS4R/credit-taxonomy/issues/4 - Contributions.  eLife will update tagging to conform with the JATS4R recommendation when it is published.

Regarding "other footnotes", eLife will _consider_ removing the necessity for them.

Thanks

**Comment by michael** [comment]
OK, I split this up into separate issues. I think we can use the footnotes for encoding as done currently but will make them separate requirements.

#1030 
#1031 
#1029 

closing this issue.
