### ISSUE TITLE
Configurator imports need to be controllable

### ISSUE THREAD

**Issue by michael** [substance/texture#544]
Currently the configurator is setup during archive construction.

https://github.com/substance/texture/blob/master/src/ArticleLoader.js#L11

This is a problematic place, since we may want to load different configurations. In my concrete case, I want to either use ReaderPackage or EditorPackage. But even if I were able to tell TextureArchive, which config to use for what article type, that still wouldn't seem quite right.

I think the problem is that archive construction already depends on app-specific configuration. When constructing the editorsession we already need to know registered commands (commandManger is setup). However for the reader, we don't need / want those commands.

@oliver---- I have a feeling we should separate model-level configuration (needed for loading an archive) vs app-level configuration (commands etc.).

I guess i can find some hack for now, but we should address this for our new app architecture.

**Comment by michael** [comment]
Using this hack for now.

https://github.com/substance/texture/blob/ea3c626eb9608a1d44e1057f2b525cdf78cbb522/src/WebAppChrome.js#L19

**Comment by michael** [comment]
@oliver---- please take a look. Reader interface is available at: http://localhost:4000/reader.html

**Comment by michael** [comment]
sorry, last comment belongs to this PR:

https://github.com/substance/texture/pull/545/files

**Comment by oliver----** [comment]
I guess the challenge now is to get generalized components for the content nodes, e.g. for a figure. ATM ContainerEditor is spawning components, and passes a node as prop. Maybe we need to override ContainerEditor's methods to pass a generalized model and an editing API. This also needs to go through the IsolatedNodeComponents layer.

**Comment by michael** [comment]
Could you help me prototype an alternative ContainerComponent that does that? We could do first for the reader, so we don't destabilise the editor and when we have the reader in place also use the new ContainerComponent and try to reuse as much as code as possible. Generally editor and reader components could have the same markup except for some ui elements (ellipsis menu etc.)

I will add some more models (e.g. for Figure) and commit into the reader branch.

**Comment by oliver----** [comment]
I could envisage to have modular editor APIs for fragments like figs etc.
For that we need a tweaked ContainerEditor and IsolatedNodeComponent, because they are meant to work on nodes.

This method would need to be overridden in a customized ContainerEditor: https://github.com/substance/substance/blob/develop/ui/ContainerEditor.js#L117-L131

And this method for a customized IsolatedNodeComponent: https://github.com/substance/substance/blob/develop/ui/AbstractIsolatedNodeComponent.js#L49-L63

**Comment by michael** [comment]
I guess we'd need a lookup mechanism for a model. Something like:

```js
let model = api.getModel(node) // this would return a FigureModel for a fig node.
```

I guess we would then switch from using the node.type to match the component to using the model.type. For figures and tables that could be a way to map table-wrap, fig etc. to a generic FigureModel.

I can try to get something working...

**Comment by oliver----** [comment]
Sounds good.
Probably we want to have a configurator for this.

**Comment by michael** [comment]
Quick update: I wanted to change the property for components from `node` to `model` so we see the different semantics. However, I don't want to break everything in this first iteration, so I will keep using node with the same generic interface (id,type, getPath for text nodes etc.).

that an ok approach?

**Comment by oliver----** [comment]
Do you mean you are adding an alias for the model named `node` or do you provide the model node?
For sake of legacy, it would make sense to add both, i.e. the model as `model`  with the new semantics and `node` as `node` with the old semantics.
After some time you would try to drop the `node` prop alltogether.

**Comment by michael** [comment]
Makes sense - will keep both as you suggested.

**Comment by michael** [comment]
@oliver---- with the separation it gets a bit blurry how to do the mapping and not just 1:1 replicating the structure we already have with the XML nodes.

E.g. in the internal XML we have:

 - `abstract > abstract-content > p*`
- `fig > caption`

fig and abstract being block nodes and abstract-content+caption being container nodes. Somehow I'd like to eliminate these extra layers in the model, but then it's not clear how. E.g. I'd want to have just one ArticleAbstractModel which acts as a container, but also store some metadata about the abstract. That's something we can't do in XML, as we need to differentiate between element nodes and container nodes. We also currently expose that in the components e.g. have:

`.sc-abstract#abstract_1 and .sc-abstract-content#abstract_content_1`

Do you have ideas how to approach this? Or is it just fine to have these layers in both the nodes and the models?

Using models in favour of nodes could affect some of Substance's core functionality. E.g. ContainerEditor works with a ContainerNode. Should this in future instead work with a ContainerModel instead? Then the ContainerModel could read and write the XMLDOM, but the API's (.e.g. what's in ContainerMixin like getnodeAt, show, hide etc.) could then be attached to ContainerModel.

**Comment by oliver----** [comment]
I guess instead of replacing Substance Data Nodes, we should let a Node 'be a' model. I.e. a TextNode is a TextModel. The same for ContainerModel and Node. etc.
As you said this will affect the very core of our implementation, thus this will take some time.
With EditingInterface and Editing (as impl) I went the have way probably, i.e. triggering manipulations for basic editing via API, rather than hard coded data paths.

To approach it step by step, I would look at the core Node classes and let them implement the Model interface and make use of it in `Editing`. There will be more places such as annotationHelpers, documetHelpers etc.
The next step would be to get the Test-suite green again (in substance)
After that you should have the basics available again, and adding models such as for figs would be pretty straight-forward.

Re the structure: in many cases the XML/JATS model is already a pretty natural representation. What you are looking for is a generalized description of concepts. E.g. a figure has a title, a caption, and a graphics. The XMLNode would be pretty close here. Still, the mission is to have a functional API for these concepts.
Re abstract: I would probably say the abstract has a body and maybe some meta.
