### ISSUE TITLE
Figures QC: permissions

### ISSUE THREAD

**Issue by michael** [substance/texture#617]
![image](https://user-images.githubusercontent.com/2931/42943538-51d1a338-8b63-11e8-834f-2da57662f1b2.png)

This reflects [JATS4R tagging](https://jats4r.org/permissions).

```xml
<article xmlns:ali="http://www.niso.org/schemas/ali/1.0" … >
...
<permissions>
 <copyright-statement>© 2014 Surname et al.</copyright-statement>
 <copyright-year>2014</copyright-year>
 <copyright-holder>Surname et al.</copyright-holder>
 <ali:free_to_read/>
 <license>
 <ali:license_ref start_date="2014-02-03"
 >http://creativecommons.org/licenses/by/4.0/</ali:license_ref>
 <license-p>This is an open access article distributed under the terms of the <ext-link
 ext-link-type="uri" xlink:href="http://creativecommons.org/licenses/by/4.0/">Creative
 Commons Attribution License</ext-link>, which permits unrestricted use, distribution,
 reproduction and adaptation in any medium and for any purpose provided that it is properly
 attributed. For attribution, the original author(s), title, publication source (PeerJ) and
 either DOI or URL of the article must be cited.</license-p>
 </license>
</permissions>
…
</article>
```

Considerations:

- only one permission exposed in UI for simplicity (multiple permissions are really an edge case and we will find some other way to support it)
- translations will just be optional fields to fill out (will be configurable which language fields are visible depending on the journal)

Questions:

- would it make sense to generate the copyright statement from fields (copyright year + copyright holder) to avoid redundancy?

@substance/texture-contributors does that sound like a valid approach? Do you like the UI proposal?

**Comment by michael** [comment]
@fabiobatalha @gustavofonseca regarding translated figures, I guess we also need translations for the figure title? If yes, can you provide some example markup?

**Comment by gustavofonseca** [comment]
@michael, we solved that as follows:

```
...
<fig-group id="f1">
    <fig xml:lang="pt">
        <label>Figura 1</label>
        <caption>
            <title>Caracterização química em óxidos do rejeito.</title>
        </caption>
    </fig>
    <fig xml:lang="en">
        <label>Figure 1</label>
        <caption>
            <title>Chemical characterization of the oxides of the tailing.</title>
        </caption>
    </fig>
    <graphic xlink:href="1234-5678-rctb-45-05-0110-gf05.tif"/>
</fig-group>
...
```

**Comment by fabiobatalha** [comment]
@michael 

We don't translate label, caption and permissions for content in the body of the document. It means we follow the language of the full text.

It is different for permissions in the ``article-meta`` that could be present in more then one language.

For us the ``copyright-statement`` is enough, we don't need to have this level of granularity for permissions.

**Comment by michael** [comment]
@gustavofonseca thank you for sharing the example. I wonder if this would lead to confusion with other fig-group use-cases? In general we understand that a fig-group is used when a figure consists of multiple graphics. 

@pdonohoe could you help us with requirements? We want to have multiple languages per label + caption and title but only one graphic.

Here's another way how we could approach it. Problem here is that no multiple labels are allowed in JATS-Archiving.

```xml
    <fig xml:lang="pt">
        <label>Figura 1</label>
        <caption xml:lang="en">
            <title>Caracterização química em óxidos do rejeito.</title>
            <p>bla blump</p>
        </caption>
        <caption xml:lang="es">
            <title>Caracterização química em óxidos do rejeito.</title>
            <p>bla blump</p>
        </caption>
    </fig>
```

@substance/texture-contributors could you all comment?

**Comment by Melissa37** [comment]
@michael In the instance above:

 _would it make sense to generate the copyright statement from fields (copyright year + copyright holder) to avoid redundancy?_ 
is not true....where is the All rights reserved that is in the statement but not in copyright year + copyright holder?
Also, this example shows a copyright and all rights reserved with a CCBY license, which is not right :-)
We might have multiple licenses for one figure...

**Comment by michael** [comment]
@Melissa37 ok we can leave the 3 fields for now, was just thinking maybe we can reduce the number of fields and speed up the workflow. 

The above example is just there to show all fields which could be filled out, so apart from wrongly stating CC-BY along with a copyright are those the right fields to display?

I think we should sit together and discuss the multi-permission use-cases (which you said are rather rare?). I've seen some examples from JATS4R with multi-panel figure images where one panel is has the permission x and another panel has a different permission. While I can see such things exist and are submitted by authors, I wonder what the consequence of such a mixed permission is? Is this really a good practice for an open access paper? It's hard to reuse that image right because it has a mixed license? I suppose the ideal case is that the whole paper is CC-BY including all images, then we'd just need to select the license once per paper. 

I'd suggest to do a first implementation with only one permission per figure until September, if that's ok? And then we could put this topic on the agenda for the Sao Paulo meeting and find agreement on how to deal with multi-permission figures.

**Comment by Melissa37** [comment]
Hi @michael! Thanks for the response and I agree it would be good to sit down and discuss. Something I often come across is the issue of editorial freedom VS standardisation and machine readability/UX etc.
We have to be careful, as does JATS, that semantic XML is required and should be promoted for reuse and interoperability, but yet the human reader is still very present, as well as any nuances of the editorial needs.

I/eLife agree in principle that having restricted content in an open access paper is far from ideal, however if an author needs to make a point and the only way to do that easily is by using an illustration from elsewhere that is published under a restrictive license, we need to account for that. The need to semantically provide this information in a machine readable way is something the author and editorial department don't really care about, but I do as unless this information is encoded within the XML, either re-use of it happens regardless and we're not fulfilling our duty, or machine readers cannot trust my CCBY licensed content as there may be hidden un-reusable content in there and so they do not reuse any of it.
The flip side is that all rights reserved publications should add a license statement when they use CCBY or other open content so a machine and person knows they can reuse it, opening up more content!

The multi-license use case is rare. If all the sections had the same license criteria, it would be OK to lump them together, but I don't think they ever do (otherwise they would be lumped together already!). Also, I have recently discovered the ali namespace requires a URL to be put in the machine readable license section. There is not a generic all rights reserved uri that can be used, so this is already a flaw in the JATS4R recommendation that requires review. Crossref requires this when delivered to them.

This is a really complicated and thorny issue! Discussion as a group would be useful :-)

**Comment by Melissa37** [comment]
Hi Michael

The data mining original use case was for wikipedia.
They want to be able to find ccby content and if there is a component of that not-ccby they need to know in a machine readable way and exclude from their re-posting.
The solution you have proposed does not cover that and is not JATS4R compliant, which was one of the basics Texture was going to support?

**Comment by michael** [comment]
@Melissa37 let's discuss this more. I was closing this as first iteration is done (for the Texture september release), where we can have one permission per figure. Before we address multiple permissions per figure, we should have agreement on how to represent figure panels. The JATS proposed way is to use fig-group and one fig per panel. I know that eLife is using fig-group to model supplementary figures. I'm not sure if that's general enough to go into the dar spec. I have a feeling that we rather want to use fig-group for modelling figure panels. Then we can address individual figures and assign permissions for each. I leave this issue open but assign to Texture 2.0 milestone.

**Comment by Melissa37** [comment]
Sure, let's talk more :-)

**Comment by michael** [comment]
Closing this as mostly done and move multi-permissions into a separate issue. #1023
