### ISSUE TITLE
Getting rid of InternalArticle XML schema

### ISSUE THREAD

**Issue by michael** [substance/texture#627]
There are some serious problems with our approach of 2 XML schemas. Especially during conversion. I've realised that we've so far programmed against the following assumption: During conversion at all times both schemas TextureArticle and InternalArticle need to be valid in order to use schema reflection (things like `schema.findFirstValidPos(parent, tagName)`)

I'm now struggling with importing / exporting the article record:

- In TextureArticle we have standard-conform tagging with strict order e.g. for (((fpage, lpage?)?, page-range?) | elocation-id)?
- In InternalArticle these elements are not allowed (as we have them inside pubMetaDb (article-record) for storing that information
- In InternalArticle we have some custom things in place such as aff-group or custom table schema 
- The importing step means that the underlying XML tree will be valid in InternalArticle but invalid in TextureArticle
- Now this is a problem because during export I want to use schema reflection to find the insertion positions for fpage,lpage where i need to rely on schema.findFirstValidPos. However, this is not possible before the xml becomes valid for TextureArticle (it's only valid after completion of all export transforms, but not in between when we need the schema information)

Proposed strategy:

- we only define TextureArticle schema
- for custom elements we use Substance models directly (e.g. for our custom table model and things like affiliations, references etc. as we do now)
- we keep the XML valid JATS at all times (e.g. interally we drop the ref-list since we have our own representation)
- I'd even go so far that on import to remove the body element from the XML because then we can use regular substance container nodes and custom models for fig + table etc. without violating the JATS schema (it's fine to keep them XML nodes for now to satisfy the implementation but then we'd be free to use flat substance models everywhere in the future)
- If we keep a reference to the original body node we could continue using el.find('') in subtrees etc.

@oliver---- what do you think about that matter? Is there an incremental path towards reaching that design without breaking too much? I'd be crucial to have a plan for this soon, as with the more complex metadata we're blocked currently. and i don't want to base the code on static assumptions (like ensure we have one anchor element in article-meta which we can use to derive element positions).

**Comment by oliver----** [comment]
First I agree with you that the more we deviate internally from JATS the more it does not make sense to try an inplace-DOM-transformation -- which I guess is causing more problems than we would like.

Beyond that, I guess it might still be difficult with a Two-DOM (or model-to-DOM) conversion strategy -- because the target DOM (=JATS DOM) would still need to be in a valid state all the time.

What we could try for export is, create a new minimal JATS DOM and generate into it. @michael would that help?

**Comment by michael** [comment]
I'm not completely sure yet. Maybe we should really think of it as a big import + export step (= end of line JATS ;-))

If we did a "full export" of article meta for instance, and assuming we have everything in some internal model, then we could hard-code the order and it would probably read more naturally.

Where it gets problematic is doing incremental transitions on an existing DOM.

But that's the more radical design we may want to have eventually one day. I'm fine with keeping some things XML-ish in the internal model, but then we should deviate from the JATS, because there it gets complicated. Means, if we do something custom, we do it outside of the DOM in regular Substance nodes.

It worked quite well to map individual elements of the doc to regular substance nodes (e.g. references etc.) and remove the original and later on export bring it back. Where it gets hard is when we introduce custom DOM structures (e.g. aff-group) and do as you say in-place transformations. 

Currently we have a mix.. which is hard to understand.

**Comment by oliver----** [comment]
Just want to make clear, that I have the feeling that there are >two things mixed here.
1. Struggling with the target schema is one thing.
2. Having a non XML internal model is another, but this is IMO not connected to this particular problem.
So my advice would be to solve the problems one after another. 
Having a non-inplace conversion is probably in-evitable, no matter if we use XML internally or not.
The problem is just that we need to rewrite the converters to generate rather transform.
Altogether I am not much in favor of doing this in a hurry. Particularly because we want to switch to Stencila ASAP.
Are there any workarounds? E.g. determining the insert position manually, not relying on schema driven insert?

**Comment by michael** [comment]
Yes I just discovered workaround. It is using article-meta as is in InternalArticle. Then use InternalArticle schema inspection to find the insert pos.

Yes we should take time for this. But better do the switch before we add the complete feature sets, as we'll write converters multiple times.

**Comment by oliver----** [comment]
FYI, we will not be able to provide a XML Editor for un-implemented features.

**Comment by oliver----** [comment]
After some sleep I have the feeling that this issue in some parts goes into the wrong direction, or at least too far.

Having an XML, or at least a structured model is not generally a bad thing. E.g. there is a natural order in XML DOMs, which for instance helped us with the numbering of references. Before we had a manual implementation, which was pretty arbitrary, and also utterly incomplete. 
Beyond that I like XML being interface that can be understood pretty well by others. In general it is nice to have a specific place where an element is stored, rather than a soup of things, relying on indexes.

I assume the essence of this issue is that the current internal XML schema is just annoying in some cases, which comes from the fact that it is derived from the JATS schema.
On the other hand, we found that for entities it is nicer to have flat plain records. 

Maybe a mixture could be interesting then, i.e. a document model which is structured like XML but where leafs can be record elements, not being restricted to having attributes and child nodes only, and not meant for hierarchical data.

Altogether I am in favor of moving towards a more handy internal model, that is not in our way. But I would not like to give up the benefits of the current XML model.

**Comment by michael** [comment]
Ok, we will not do this. Instead improve on the current approach and merge pubMetaDb and document (as discussed this morning).
