### ISSUE TITLE
Global event handling to override or suppress OS behavior.

### ISSUE THREAD

**Issue by Integral** [substance/texture#723]
To suppress undesired native behavior we have to suppress certain key-combos on application level.
Some of them still need to be discussed, as they might still desired by the user:
- `CMD-Q`
- `CMD-W`
- `CMD-A`

**Comment by Integral** [comment]
@oliver---- let's do it here
are sure that we want to shutup even cmd+q?

**Comment by oliver----** [comment]
Let's start a list, and include @michael in the discussion.
`CMD+q` could indeed be a candidate that we do not want to touch.

**Comment by Integral** [comment]
CMD+w, CMD+a?

**Comment by oliver----** [comment]
`CMD+W` we probably shouldn't.
However, in a multi-doc-like environment it is tempting to use it, e.g. in Chrome Debugger I often accidentally close the window.

**Comment by oliver----** [comment]
`CMD+A` is definitely application land.

**Comment by michael** [comment]
Let's find unproblematic keys for now, that are not overloaded. CMD+OPTION+something is fine for most cases. We will get the user reports of what they'd like to use as a shortcut. So I think we should post an issue with a table of current shortcuts and let people make suggestions.

**Comment by oliver----** [comment]
We still should need a decision, about overriding certain OS specific short-cuts, e.g. should `Cmd-W` close the tab in the browser, or not. This problem arises, because we are implementing an app inside the browser. In the desktop version there is a natural answer, `Cmd+W` should be used to close the current tab (if we had this).
Beyond the obligatory ones which are dominated by existing patterns, the specific definition of shortcuts is not relevant now. The maybe more interesting question is how to customize them.

**Comment by oliver----** [comment]
Notice, that some native behavior does not make sense and lead to an undesired behavior.
E.g. letting `Cmd-A` pass would maybe select a part of the displayed HTML.

**Comment by oliver----** [comment]
And there is the guide-line for this discussion: If the native behavior is influencing Texture in an undesired way, we have to suppress it.

**Comment by oliver----** [comment]
Also notice @Integral's comment about browser plugins. It could even be necessary to only let pass a white list of combos to avoid that a custom browser plugin is taking over control and disrupting Texture.

**Comment by oliver----** [comment]
Done via 783
