### ISSUE TITLE
Can't type replace string (will be filled into search string)

### ISSUE THREAD

**Issue by michael** [substance/texture#791]

**Comment by oliver----** [comment]
> in metadata panel, we may want to search also the labels (even if not replace them). for instance i want to look up "footnotes", it should take me to the footnotes section

This I would argue is a very questionable feature, because is it is not done on the model content, but on the application chrome. Maybe there could be some search extensions where the search engine suggests extra results (~topics), such as TOC entries, but not as an editable text fragment.
And then it would probably rather be a different dialog, than the find in text dialog.

**Comment by oliver----** [comment]
> - not possible to control the selected match while editing (cmd+g, cmd+shift+g are supposed to work, and with enter you would replace instance by instance)

There are no keyboard shortcut registered in the moment. Keyboard shortcuts in general are pretty platform and even application related. So we should address that as a general task, not restricted to this one only.

**Comment by michael** [comment]
Ok, let's name this issue after the bug. And have the other non-critical things in separate issues.

**Comment by oliver----** [comment]
Fixed via #865
