### ISSUE TITLE
Do not fail when document contains elements that are not implemented 

### ISSUE THREAD

**Issue by axfelix** [substance/texture#943]
I know I've opened discussions like this in the past, but I'm wondering if Texture can be made to silently discard JATS elements which currently throw "not implemented yet" errors -- the implication being that they're definitely planned for implementation because it doesn't make sense for Dar to omit them (e.g. `<journal-meta>`, `<ack>`, `<table-wrap-foot>`) -- rather than dying on import.

I'm still uncomfortable trying to tool around these to make sure our importer will drop them properly since we expect Dar to change somewhat in the short term. There are some elements that I'd expect Texture to just discard rather than dying on if it doesn't like them (e.g. `<hr/>`) but I think that's a separate issue.

**Comment by fabiobatalha** [comment]
Hi @axfelix 

What you mean with silently discard?

I'm concerned discarding elements Texture is not supporting yet. In my opinion these elements should be bypassed with no changes.

For example, lets say an author have a ``<bio>`` element that is still not supported in Texture. The expected behaviour is, to keep this element in the final XML file without any change.

Discard this element lead to unpredictable loss of data.

**Comment by axfelix** [comment]
Yes, also fine longer-term! I just don't want them blocking import right now.

**Comment by oliver----** [comment]
ATM, we have made Texture strict, so that we see where we actually are.
Still, I have left a 'hidden' feature, allowing for unsupported elements passed through. You can enable this via query-parameter: `?allowNotImplemented=true`.

Entire block-level elements, or inline-elements, which Texture does not take responsibility for, are then displayed as grey-boxes with the XML string as content.

**Comment by fabiobatalha** [comment]
This functionality should work in the stand alone version while opening a file.
