### ISSUE TITLE
Allow for MathML as source for inline-formula and disp-formula

### ISSUE THREAD

**Issue by oliver----** [substance/texture#956]
Requested by @JGilbert-eLife:

> MathML is not yet supported in the XML or the interface

**Comment by oliver----** [comment]
In my opinion, MathML is a problematic source format for math, as it is very display oriented.
Browsers stopped supporting it natively.

**Comment by JGilbert-eLife** [comment]
It is problematic, but what else do we use? As I understand it, we currently need to use MathML as it's the only way to display equations as actual text rather than as flat images. We want to avoid using images at all costs, so for now I assume that eLife at least will NEED to use MathML.

Alternative suggestions welcome of course, but this might not be a requirement we can get around.

**Comment by michael** [comment]
@JGilbert-eLife Before we look into solutions for supporting MathML, I'd like to verify why TeX-Math would not be enough as a source format. Can you elaborate use-cases?

**Comment by Melissa37** [comment]
>What do you think, @Melissa37 ? Have I outlined that correctly?

I think so! I think we need to have a wider discussion on this with eLife Devs involved and perhaps someone like Peter Krautzberger @pkra too.

- To get old content into Texture (which will be an eLife requirement to deal with new versions and corrections) it will need to be able to accept MathML as that's what eLife stores Math in currently. Unless there is a conversion process on our archive
- Tex-Math is an equation editor? So that's more about the user interface for editing than the output?
- Authors editing will prefer to have an interface that allows them to use LaTex
- We currently use MathJax to display our on the website, but our input has always been MathML, so I don't know whether that would pose problems for our site/our processes
- I don't know what most publishers use, but we'd not want Texture to be inaccessible to a lot of publishers because it does not support MathML output
- I don't know what I am talking about, but I know simple LaTex is not simple and causes so many problems for the workflow and I see conversion to MathML as a way to standardise input from authors that has used LaTex to make something "look right" in a PDF rather than machine-readable and comparable across a corpus

**Comment by michael** [comment]
As discussed with Melissa in yesterday's call we can go with TeXMath as an input (which I think is a great choice). So I'm closing this issue.
